// Auth action types
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
export const LOGOUT = "LOGOUT"
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS"
export const AUTH_CHECK_FAILURE = "AUTH_CHECK_FAILURE"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"

// Book action types
export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST"
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"
export const FETCH_BOOK_DETAILS_REQUEST = "FETCH_BOOK_DETAILS_REQUEST"
export const FETCH_BOOK_DETAILS_SUCCESS = "FETCH_BOOK_DETAILS_SUCCESS"
export const FETCH_BOOK_DETAILS_FAILURE = "FETCH_BOOK_DETAILS_FAILURE"
export const FETCH_FEATURED_BOOKS_SUCCESS = "FETCH_FEATURED_BOOKS_SUCCESS"
export const FETCH_NEW_RELEASES_SUCCESS = "FETCH_NEW_RELEASES_SUCCESS"
export const FETCH_RELATED_BOOKS_SUCCESS = "FETCH_RELATED_BOOKS_SUCCESS"
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"

// Cart action types
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY"
export const CLEAR_CART = "CLEAR_CART"

// Order action types
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE"
export const FETCH_ORDER_DETAILS_REQUEST = "FETCH_ORDER_DETAILS_REQUEST"
export const FETCH_ORDER_DETAILS_SUCCESS = "FETCH_ORDER_DETAILS_SUCCESS"
export const FETCH_ORDER_DETAILS_FAILURE = "FETCH_ORDER_DETAILS_FAILURE"
export const FETCH_USER_ORDERS_REQUEST = "FETCH_USER_ORDERS_REQUEST"
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS"
export const FETCH_USER_ORDERS_FAILURE = "FETCH_USER_ORDERS_FAILURE"

